version: "3.9"
services:

  influxdb:
    container_name: wf-influxdb
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - ./cache/influx:/var/lib/influxdb
      - ./cache/influx/temp/influxdbv2:/var/lib/influxdb2:rw
#    environment:
#      - DOCKER_INFLUXDB_INIT_USERNAME=username
#      - DOCKER_INFLUXDB_INIT_PASSWORD=password
#      - DOCKER_INFLUXDB_INIT_ORG=kayo
#      - INFLUXDB_DB=kayo
#      - INFLUXDB_ADMIN_USER=username
#      - INFLUXDB_ADMIN_PASSWORD=password
#      - DOCKER_INFLUXDB_INIT_BUCKET=kayo

  postgres:
    image: postgres:13.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./cache/postgresql:/var/lib/postgresql/data
